const CONSOLE_OUTPUT = "CONSOLE_OUTPUT";
const LOGENTRIES_OUTPUT = "LOGENTRIES_OUTPUT";
const SILENT_OUTPUT = "SILENT_OUTPUT";


const constants = {
  CONSOLE_OUTPUT,
  LOGENTRIES_OUTPUT,
  SILENT_OUTPUT,
  ALL_OUTPUT_DESTINATIONS: [CONSOLE_OUTPUT, LOGENTRIES_OUTPUT, SILENT_OUTPUT]
};

module.exports = constants;
